Add basic markdown html sanitizer
vlang/vpm pull request #116
Opened 2023-09-29 10:00 UTC by Terisback

Reference: https://github.com/rhysd/marked-sanitizer-github

2023-09-29 11:27 UTC, ArtemkaKun requested changes

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +// import encoding.html as enc_html
Remove if not needed or add a comment about why it should stay

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +]
Mark as fixed array

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +]
Mark as fixed array

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +							'x-github-client'] {
Mark as fixed array

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +			tag.name in ['blockquote', 'del', 'ins', 'q'] {
Mark as fixed array

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +						if url.scheme in ['http', 'https'] {
Mark as fixed array

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +					if k in ['src', 'longdesc'] {
Mark as fixed array

2023-09-29 11:27 UTC, ArtemkaKun commented on src/lib/html/sanitize.v
> +						if url.scheme in ['http', 'https'] {
Mark as fixed array

2023-09-29 11:59 UTC, ArtemkaKun approved these changes

2023-09-29 15:05 UTC, spytheman commented on src/lib/html/sanitize.v
> +							'x-github-client'] {
There is no need for that, and it can harm the readability of the program. v optimizes that out, to a bunch of string__eq() || string__eq() ... calls, without creating an intermediate array.

2023-09-29 15:05 UTC, spytheman commented on src/lib/html/sanitize.v
> +			tag.name in ['blockquote', 'del', 'ins', 'q'] {
no need

2023-09-29 15:08 UTC, merged

2023-09-29 21:27 UTC, Le0Developer commented on src/lib/html/sanitize.v
> +				println('met ${tag.name} EXTERMINATE')
uh?

2023-09-30 02:15 UTC, spytheman commented on src/lib/html/sanitize.v
> +				println('met ${tag.name} EXTERMINATE')
I also wondered about it, but looking at the next match, it seems, that there is a tendency to add more checks in that piece of code, and with the match, adding those will be easier (produce a smaller diff).

As for the println call, the context, is that module is going to be used in `vpm`, which is a webserver, i.e. that line will not be seen by users at all, but by the administrators of the machine that runs vpm. Imho it is good to have it, in fact it could be even more informative, like include a timestamp, and perhaps show more context about the tag, not just the name.

2023-09-30 02:19 UTC, spytheman commented on src/lib/html/sanitize.v
> +				println('met ${tag.name} EXTERMINATE')
btw, `log.warn('met ${tag.name} EXTERMINATE')` could be used to add a timestamp, and a label, so that it will be easier to search for in the output.